language: node_js

node_js:
  - '5'
  - '4'
  - '0.12'

addons:
  code_climate:
    repo_token: 8192c6f12135ab1ce39ac2da163bf8ee2c764e419d41fbc1be2441d35432224c

before_install:
  - npm i -g codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
